apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- $annotations := fromYaml (include "datasetsServer.ingress.annotations" .) }}
  annotations: {{ toYaml $annotations | nindent 4 }}
  labels: {{ include "labels.reverseProxy" . | nindent 4 }}
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ include "datasetsServer.ingress.hostname" . }}
      http:
        paths:
          - backend:
              service:
                name: "{{ include "name" . }}-reverse-proxy"
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  {{- if include "common.ingress.certManagerRequest" ( dict "annotations" $annotations ) }}
  tls:
    - hosts:
        - {{ include "datasetsServer.ingress.hostname" . }}
      secretName: {{ printf "%s-tls" (include "datasetsServer.ingress.hostname" .) }}
  {{- else if .Values.ingress.tls -}}
  tls: {{toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
